import { WORKSPACE_CONTRACT_VERSION } from "@codexhost/shared-contracts";

export type {
  HarnessCredentialTransfer,
  HarnessCredentialExport,
  HarnessCredentialImports,
} from "./credential-imports.js";
export { validateHostApprovalResponse } from "./approval.js";
export { validateHostInteractionResponse } from "./interaction.js";
export { HarnessOutputChannel } from "./output-channel.js";
export { sanitizeDiagnosticTail, filterAmbientNodeWarnings } from "./diagnostics.js";
export { validateHostQuestionResponse } from "./question.js";
export { parseHostUsage } from "./usage.js";
export type { HostUsage } from "./usage.js";
export type {
  AutonomousTurnStartedEvent,
  CreateSessionInput,
  ForkSessionInput,
  HarnessAdapter,
  HarnessCommandAccepted,
  HarnessCommandCapability,
  HarnessCommandInvocation,
  HarnessError,
  HarnessErrorCode,
  HarnessExecutionPolicy,
  HarnessInspection,
  HarnessModel,
  HarnessModelCatalog,
  HarnessModelRef,
  HarnessPermissionMode,
  HarnessPermissionModeCatalog,
  HarnessPermissionModeId,
  HarnessOutput,
  HarnessResult,
  HarnessSession,
  HarnessSessionCapabilities,
  HarnessSessionImportCandidate,
  HarnessSessionImportCapability,
  HarnessSessionImportSource,
  HarnessSubagentCapability,
  HarnessWebUiAction,
  HarnessSessionState,
  HarnessThinkingOption,
  HarnessThinkingOptionId,
  HostAgentMessageItem,
  HostApprovalAction,
  HostApprovalEffect,
  HostApprovalInteraction,
  HostApprovalResponse,
  HostChoiceQuestion,
  HostCommand,
  HostCommandExecutionItem,
  HostContextCompactionItem,
  HostEvent,
  HostFileChange,
  HostFileChangeItem,
  HistoricalTurnOutcome,
  HostInteraction,
  HostInteractionResponse,
  HostItem,
  HostItemOutcome,
  HostItemSnapshot,
  HostItemUpdate,
  HostQuestion,
  HostQuestionInteraction,
  HostQuestionResponse,
  HostReasoningItem,
  HostSubagentDelegationItem,
  HostSubagentState,
  HostSubagentStatus,
  HostThreadSnapshot,
  HostTextInput,
  HostTextQuestion,
  HostToolExecutionItem,
  HostToolOutput,
  HostTurnSnapshot,
  InteractionClosedEvent,
  InteractionRespondAccepted,
  InteractionRespondCommand,
  ItemCompletedEvent,
  ItemStartedEvent,
  InspectHarnessInput,
  ItemUpdatedEvent,
  ModelSelectCommand,
  ModelSelectCompleted,
  OpenSessionInput,
  PermissionModeSelectCommand,
  PermissionModeSelectCompleted,
  ResumeSessionInput,
  RollbackLastTurnSessionInput,
  SessionFaultedEvent,
  SessionStateChangedEvent,
  SessionUsageChangedEvent,
  SubagentStateChangedEvent,
  SubagentTranscriptChangedEvent,
  ThinkingSelectCommand,
  ThinkingSelectCompleted,
  TurnCompletedEvent,
  TurnCancelAccepted,
  TurnCancelCommand,
  TurnOutcome,
  TurnStartAccepted,
  TurnStartCommand,
  TurnStartedEvent,
} from "./text-session.js";

export const packageMetadata = {
  name: "@codexhost/harness-adapter",
  contractVersion: WORKSPACE_CONTRACT_VERSION,
} as const;
export {
  COMMON_EXCLUDED_LIVE_COMMAND_PREFIXES,
  COMMON_EXCLUDED_LIVE_COMMANDS,
  LiveHarnessCommandCatalog,
  isExcludedLiveCommand,
  liveHarnessCommandPrompt,
  mergeLiveHarnessCommands,
  type LiveCommandExclusions,
  type LiveHarnessCommand,
} from "./live-command-catalog.js";
